apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-ecommerce-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: site-ecommerce-pv